name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          python -m virtualenv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt
      - name: Run migrations
        run: |
          source venv/bin/activate
          python backend/manage.py migrate --settings=climate_insights_backend.settings
      - name: Run tests
        run: |
          source venv/bin/activate
          python backend/manage.py test --settings=climate_insights_backend.settings
        


